name: Roborazzi Integration Tests

on:
  push:
    branches: [ master, 'robolectric-*.x' ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master, google ]
    paths-ignore:
      - '**.md'

permissions:
  contents: write # for uploading screenshots

jobs:
  roborazzi_tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2.11.0

      - name: Run unit tests
        id: roborazziverify
        continue-on-error: true
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew :integration_tests:roborazzi:verifyRoborazziDebug \
          --info --stacktrace --continue \
          --parallel \
          --no-watch-fs \
          -Drobolectric.alwaysIncludeVariantMarkersInTestName=true \
          -Dorg.gradle.workers.max=2

      - name: Prevent pushing new screenshots if this is a fork
        id: checkfork
        continue-on-error: false
        if: steps.roborazziverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1

        # Runs if previous job failed
      - name: Generate new screenshots if verification failed and it's a PR
        id: roborazzirecord
        if: steps.roborazziverify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew :integration_tests:roborazzi:recordRoborazziDebug \
          --info --stacktrace --continue \
          --parallel \
          --no-watch-fs \
          -Dorg.gradle.workers.max=2

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.roborazzirecord.outcome == 'success'
        with:
          file_pattern: '*/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test_results
          path: |
            **/build/reports/*
            **/src/screenshots/*
            **/build/outputs/roborazzi/*

